version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
    time: "15:00"
  open-pull-requests-limit: 10
  reviewers:
  - mdgreenwald
  labels:
  - "npm"
  - "dependencies"
- package-ecosystem: "docker"
  # Files stored in repository root
  directory: "/"
  schedule:
    interval: "monthly"
    time: "15:00"
  open-pull-requests-limit: 10
  reviewers:
  - mdgreenwald
  labels:
  - "docker"
  - "dependencies"
